### ISSUE TITLE
iphone sizing issues

### ISSUE THREAD

**Issue by yashjagtap23** [Ph1so/FitAnalyzer#5]
<img width="792" alt="Screenshot 2024-06-24 at 4 40 27 PM" src="https://github.com/Ph1so/fitness-trainer/assets/108370176/b4b0fe23-8068-4225-94f2-7f2a8c65ab7e">

lets focus on developing this for a mobile view first since most users will use their phone. Later we can switch to a desktop support

**Comment by Ph1so** [comment]
Good point. lets use @media (max-width: 768px) {}
